---

docker_images:
  - "golang:1.10.0"
  - "alpine:latest"

build_images:
  - name: tcis/apiserver
    path: "{{ repo_dir }}/apiserver"
    dockerfile: "{{ repo_dir }}/apiserver/Dockerfile"
    type: golang
